<?php

/* This file is generated by the open source Parm Generator. github.com/cassell/Parm */

    namespace app\models;

interface MPostTable
{
    const ID_COLUMN = 'id';
    const TITLE_COLUMN = 'title';
    const CONTENT_COLUMN = 'content';
    const CREATED_AT_COLUMN = 'created_at';
    const STATUS_COLUMN = 'status';

}