<?php

/* This file is generated by the open source Parm Generator. github.com/cassell/Parm */

    namespace app\models;

trait MPostTableFunctions
{
	/**
	 * Get the "logical" table name associated. The configuration can point to a different database name.
	 * @return string
     */
	static function getDatabaseName()
	{
		return 'mvc';
	}

	/**
	 * Get the table name associated with this object
	 * @return string
     */
	public static function getTableName()
	{
		return 'm_post';
	}

    /**
     * Get the column name of the primary key field
     * @return string The primary key column name
     */
    public static function getIdField()
    {
        return MPostTable::ID_COLUMN;
    }

	/**
	 * Get the factory associated with this object
	 * @return MPostDaoFactory A DAO Factory
     */
	static function getFactory(\Parm\DatabaseNode $databaseNode = null)
	{
		return new MPostDaoFactory($databaseNode);
	}
	
	/**
	 * Get the list of columns in m_post from logical database "mvc"
	 * @return Array Array of field names
     */
	public static function getFields()
	{
		return array(self::ID_COLUMN, self::TITLE_COLUMN, self::CONTENT_COLUMN, self::CREATED_AT_COLUMN, self::STATUS_COLUMN);
	}

	/**
	 * Load an object associated with this factory
	 * @return MPostDaoObject An object built from a row out of the database table
	 */
	public function loadDataObject(Array $row)
	{
		return new MPostDaoObject($row);
	}
	
	final function getDefaultRow()
	{
		return array(self::ID_COLUMN => null, self::TITLE_COLUMN => null, self::CONTENT_COLUMN => null, self::CREATED_AT_COLUMN => null, self::STATUS_COLUMN => '0');
	}

}

?>