<?php

/* This file is generated by the open source Parm Generator. github.com/cassell/Parm */

    namespace app\models;

interface MUserTable
{
    const ID_COLUMN = 'id';
    const LOGIN_COLUMN = 'login';
    const NAME_COLUMN = 'name';
    const AVATAR_COLUMN = 'avatar';
    const PASSWORD_COLUMN = 'password';

}