<?php

/* This file is generated by the Parm Generator. github.com/cassell/Parm */

    namespace app\models;

class MUserDaoFactory extends \Parm\DataAccessObjectFactory  implements MUserTable
{
    use MUserTableFunctions;


}
