<?php

/* This file is generated by the open source Parm Generator. github.com/cassell/Parm */

    namespace app\models;

trait MUserTableFunctions
{
	/**
	 * Get the "logical" table name associated. The configuration can point to a different database name.
	 * @return string
     */
	static function getDatabaseName()
	{
		return 'mvc';
	}

	/**
	 * Get the table name associated with this object
	 * @return string
     */
	public static function getTableName()
	{
		return 'm_user';
	}

    /**
     * Get the column name of the primary key field
     * @return string The primary key column name
     */
    public static function getIdField()
    {
        return MUserTable::ID_COLUMN;
    }

	/**
	 * Get the factory associated with this object
	 * @return MUserDaoFactory A DAO Factory
     */
	static function getFactory(\Parm\DatabaseNode $databaseNode = null)
	{
		return new MUserDaoFactory($databaseNode);
	}
	
	/**
	 * Get the list of columns in m_user from logical database "mvc"
	 * @return Array Array of field names
     */
	public static function getFields()
	{
		return array(self::ID_COLUMN, self::LOGIN_COLUMN, self::NAME_COLUMN, self::AVATAR_COLUMN, self::PASSWORD_COLUMN);
	}

	/**
	 * Load an object associated with this factory
	 * @return MUserDaoObject An object built from a row out of the database table
	 */
	public function loadDataObject(Array $row)
	{
		return new MUserDaoObject($row);
	}
	
	final function getDefaultRow()
	{
		return array(self::ID_COLUMN => null, self::LOGIN_COLUMN => null, self::NAME_COLUMN => null, self::AVATAR_COLUMN => null, self::PASSWORD_COLUMN => null);
	}

}

?>